controllers/AuthenticationController.php
<?php

namespace app\controllers;

use app\models\dto\LoginForm;
use app\models\dto\RegistrationForm;
use app\services\AuthenticationService;
use app\services\AuthenticationServiceInterface;
use Yii;
use yii\base\Module;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\IdentityInterface;
use yii\widgets\ActiveForm;

class AuthenticationController extends Controller
{
    public $layout = '//authentication';

    /**
     * @var AuthenticationServiceInterface $authenticationService
     */
    private $authenticationService;

    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow'   => true,
                        'actions' => ['login', 'register', 'register-validation'],
                        'roles'   => ['?'],
                    ],
                    [
                        'allow'   => true,
                        'actions' => ['logout'],
                        'roles'   => ['@'],
                    ]
                ],
            ],
        ];
    }

    /**
     * AuthenticationController constructor.
     * @param string $id
     * @param Module $module
     * @param AuthenticationServiceInterface $authenticationService
     * @param array $config
     */
    public function __construct(string $id,
                                Module $module,
                                AuthenticationServiceInterface $authenticationService,
                                array $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->authenticationService = $authenticationService;
    }

    public function actionLogin()
    {
        $request = Yii::$app->getRequest();
        $model   = new LoginForm;

        if ($request->isGet) {
            return $this->render('login', compact('model'));
        }

        if (!$model->load($request->post()) || !$model->validate()) {
            return $this->redirect($request->getReferrer());
        }

        $session        = Yii::$app->getSession();
        $authentication = $this->authenticationService->login($model);

        if ($authentication === AuthenticationService::LOGIN_USER_CANNOT_BE_FOUND) {
            $session->setFlash('danger', 'User cannot be found.');
            return $this->redirect($request->getReferrer());
        }

        if ($authentication === AuthenticationService::LOGIN_PASSWORD_MISMATCHED) {
            $session->setFlash('danger', 'Password mismatched');
            return $this->redirect($request->getReferrer());
        }

        if ($authentication instanceof IdentityInterface) {
            Yii::$app->getUser()->login($authentication);
        }

        return $this->redirect('/home/index');
    }

    public function actionRegister()
    {
        $request = Yii::$app->getRequest();
        $model   = new RegistrationForm;

        if ($request->isGet) {
            return $this->render('register', compact('model'));
        }

        if ($model->load($request->post()) && $this->authenticationService->register($model)) {
            return $this->redirect('/home/index');
        }

        return $this->redirect($request->getReferrer());
    }

    public function actionRegisterValidation()
    {
        $request = Yii::$app->getRequest();

        if (!$request->isAjax || !$request->isPost) {
            throw new BadRequestHttpException('Request method of validating user should be invoked asynchronously.');
        }

        $model = new RegistrationForm;

        if ($model->load($request->post())) {
            return $this->asJson(ActiveForm::validate($model));
        }
    }

    public function actionLogout()
    {
        Yii::$app->getUser()->logout();
        return $this->redirect(Yii::$app->getUser()->loginUrl);
    }
}

controllers/UserAppointmentsController.php
<?php

namespace app\controllers;

use app\models\searches\UserAppointmentsSearch;
use yii\web\Controller;

class UserAppointmentsController extends Controller
{
    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel  = new UserAppointmentsSearch;
        $dataProvider = $searchModel->search($_GET);
        return $this->render('index', compact('searchModel', 'dataProvider'));
    }
}

views/layouts/authentication.php
<?php

/* @var $this View */
/* @var $content string */

use app\assets\MainApplicationAsset;
use yii\bootstrap\Alert;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;
use yii\web\View;

MainApplicationAsset::register($this);

$this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php
    $this->beginBody(); ?>

    <div class="wrap">
        <?php

        NavBar::begin([
            'brandLabel' => Yii::$app->name,
            'brandUrl'   => Yii::$app->homeUrl,
            'options'    => [
                'class' => 'navbar-inverse',
            ],
        ]);

        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items'   => [
                ['label' => 'Login',    'url' => ['/authentication/login']],
                ['label' => 'Register', 'url' => ['/authentication/register']]
            ]
        ]);

        NavBar::end();
        ?>
    </div>

    <div class="container">
    <?php
        foreach (Yii::$app->getSession()->getAllFlashes() as $type => $message) {
            echo Alert::widget([
                'body'    => $message,
                'options' => ['class' => "alert alert-{$type}"]
            ]);
        }

        echo $content;
        $this->endBody();
    ?>
    </div>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this View */
/* @var $content string */

use app\assets\MainApplicationAsset;
use Firebase\JWT\JWT;
use yii\bootstrap\Alert;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\Breadcrumbs;

$this->registerCssFile('//cdn.jsdelivr.net/npm/fullcalendar@3.10.1/dist/fullcalendar.print.min.css', ['media' => 'print', 'position' => View::POS_HEAD]);

MainApplicationAsset::register($this);

$this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>

<body>
<?php
    $this->beginBody(); ?>

    <div class="wrap">
        <?php

        NavBar::begin([
            'brandLabel' => Yii::$app->name,
            'brandUrl'   => Yii::$app->homeUrl,
            'options'    => [
                'class' => 'navbar-inverse',
            ],
        ]);

        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items'   => [
                [
                    'label' => 'Lawyers',
                    'url'   => ['/lawyers']
                ],
                [
                    'label' => 'Citizens',
                    'url'   => ['/citizens']
                ],
                [
                    'label' => 'Schedule',
                    'url'   => ['/schedule']
                ],
                [
                    'label' => 'Appointments',
                    'url'   => ['/user-appointments/index']
                ],
                [
                    'label' => 'Profile (' . (Yii::$app->getUser()->identity->getIsCitizen() ? 'Citizen' : 'Lawyer') . ')',
                    'url'   => ['/profile/personal-information', 'userId' => JWT::urlsafeB64Encode(Yii::$app->getUser()->identity->getId())]
                ],
                '<li>' . Html::a('Logout (' . Yii::$app->user->identity->username . ')', Url::to(['/authentication/logout']), ['class' => 'btn btn-link logout']) . '</li>'
            ]
        ]);

        NavBar::end();
        ?>
    </div>

    <div class="container">
    <?php
        foreach (Yii::$app->getSession()->getAllFlashes(true) as $type => $message) {
            echo Alert::widget([
                'body'    => $message,
                'options' => ['class' => "alert alert-{$type}"]
            ]);
        }

        echo Breadcrumbs::widget([
            'encodeLabels' => false,
            'links'        => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]);

        echo $content;
        $this->endBody();
    ?>
    </div>
</body>

</html>
<?php $this->endPage() ?>