controllers/AuthenticationController.php
<?php

namespace app\controllers;

use app\models\dto\LoginForm;
use app\models\dto\RegistrationForm;
use app\services\AuthenticationService;
use app\services\AuthenticationServiceInterface;
use Yii;
use yii\base\Module;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\IdentityInterface;
use yii\widgets\ActiveForm;

class AuthenticationController extends Controller
{
    public $layout = '//authentication';

    /**
     * @var AuthenticationServiceInterface $authenticationService
     */
    private $authenticationService;

    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow'   => true,
                        'actions' => ['login', 'register', 'register-validation'],
                        'roles'   => ['?'],
                    ],
                    [
                        'allow'   => true,
                        'actions' => ['logout'],
                        'roles'   => ['@'],
                    ]
                ],
            ],
        ];
    }

    /**
     * AuthenticationController constructor.
     * @param string $id
     * @param Module $module
     * @param AuthenticationServiceInterface $authenticationService
     * @param array $config
     */
    public function __construct(string $id,
                                Module $module,
                                AuthenticationServiceInterface $authenticationService,
                                array $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->authenticationService = $authenticationService;
    }

    public function actionLogin()
    {
        $request = Yii::$app->getRequest();
        $model   = new LoginForm;

        if ($request->isGet) {
            return $this->render('login', compact('model'));
        }

        if (!$model->load($request->post()) || !$model->validate()) {
            return $this->redirect($request->getReferrer());
        }

        $session        = Yii::$app->getSession();
        $authentication = $this->authenticationService->login($model);

        if ($authentication === AuthenticationService::LOGIN_USER_CANNOT_BE_FOUND) {
            $session->setFlash('danger', 'User cannot be found.');
            return $this->redirect($request->getReferrer());
        }

        if ($authentication === AuthenticationService::LOGIN_PASSWORD_MISMATCHED) {
            $session->setFlash('danger', 'Password mismatched');
            return $this->redirect($request->getReferrer());
        }

        if ($authentication instanceof IdentityInterface) {
            Yii::$app->getUser()->login($authentication);
        }

        return $this->redirect('/home/index');
    }

    public function actionRegister()
    {
        $request = Yii::$app->getRequest();
        $model   = new RegistrationForm;

        if ($request->isGet) {
            return $this->render('register', compact('model'));
        }

        if ($model->load($request->post()) && $this->authenticationService->register($model)) {
            return $this->redirect('/home/index');
        }

        return $this->redirect($request->getReferrer());
    }

    public function actionRegisterValidation()
    {
        $request = Yii::$app->getRequest();

        if (!$request->isAjax || !$request->isPost) {
            throw new BadRequestHttpException('Request method of validating user should be invoked asynchronously.');
        }

        $model = new RegistrationForm;

        if ($model->load($request->post())) {
            return $this->asJson(ActiveForm::validate($model));
        }
    }

    public function actionLogout()
    {
        Yii::$app->getUser()->logout();
        return $this->redirect(Yii::$app->getUser()->loginUrl);
    }
}

views/authentication/login.php
<?php

/* @var $this View */
/* @var $model LoginForm */

use app\models\dto\LoginForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\ActiveForm; ?>

<?php $form = ActiveForm::begin([
    'options' => ['class' => 'login-form'],
    'action'  => Url::to(['/authentication/login']),
    'method'  => 'POST'
]); ?>

<?= $form->field($model, 'identifier')->textInput(); ?>

<?= $form->field($model, 'password')->passwordInput(); ?>

<?= Html::submitButton('Login', ['class' => 'btn btn-success']); ?>

<?php ActiveForm::end(); ?>

views/authentication/register.php
<?php

/* @var $this View */
/* @var $model RegistrationForm */

use app\models\dto\RegistrationForm;
use app\models\UserType;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\ActiveForm;

$form = ActiveForm::begin([
    'options'              => ['class' => 'registration-form'],
    'action'               => Url::to(['/authentication/register']),
    'enableAjaxValidation' => true,
    'validationUrl'        => Url::to(['/authentication/register-validation'])
]);

echo $form->field($model, 'first_name')->textInput();

echo $form->field($model, 'last_name')->textInput();

echo $form->field($model, 'username')->textInput();

echo $form->field($model, 'email')->textInput();

echo $form->field($model, 'password')->passwordInput();

echo $form->field($model, 'confirmPassword')->passwordInput();

echo $form->field($model, 'type_id')->dropDownList(ArrayHelper::map(UserType::find()->all(), 'id', 'name'), [
    'prompt' => 'Select User Type'
]);

echo Html::submitButton('Register', ['class' => 'btn btn-success']);

ActiveForm::end();