controllers/CitizenAppointmentsController.php
<?php

namespace app\controllers;

use app\models\Appointments;
use app\models\AppointmentStatus;
use app\models\dto\ApproveOrRejectAppointmentForm;
use app\models\dto\CitizenAppointmentForm;
use app\services\CitizenAppointmentsServiceInterface;
use http\Exception\InvalidArgumentException;
use HttpRequestMethodException;
use Yii;
use yii\base\Module;
use yii\filters\AccessControl;
use yii\helpers\Html;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\widgets\ActiveForm;

class CitizenAppointmentsController extends Controller
{
    /**
     * @var CitizenAppointmentsServiceInterface $citizenAppointmentsService
     */
    private $citizenAppointmentsService;

    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow'      => true,
                        'actions'    => ['view'],
                        'roles'      => ['previewAppointment'],
                        'roleParams' => function() {
                            return ['appointmentId' => Yii::$app->request->get('appointmentId')];
                        },
                    ],
                    [
                        'allow'      => true,
                        'actions'    => ['create', 'validation'],
                        'roles'      => ['Citizen']
                    ],
                    [
                        'allow'      => true,
                        'actions'    => ['update'],
                        'roles'      => ['updateAppointment', 'Citizen'],
                        'roleParams' => function() {
                            return ['appointmentId' => Yii::$app->request->get('appointmentId')];
                        },
                    ],
                    [
                        'allow'      => true,
                        'actions'    => ['delete'],
                        'roles'      => ['deleteAppointment'],
                        'roleParams' => function() {
                            return ['appointmentId' => Yii::$app->request->get('appointmentId')];
                        },
                    ]
                ],
            ],
        ];
    }

    /**
     * CitizenAppointmentsController constructor.
     * @param string $id
     * @param Module $module
     * @param CitizenAppointmentsServiceInterface $citizenAppointmentsService
     * @param array $config
     */
    public function __construct(string $id,
                                Module $module,
                                CitizenAppointmentsServiceInterface $citizenAppointmentsService,
                                array $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->citizenAppointmentsService = $citizenAppointmentsService;
    }

    public function actionView($appointmentId)
    {
        $model = ApproveOrRejectAppointmentForm::find()->joinWith(['userAppointment', 'status'])
                                                       ->where(['appointments.id' => $appointmentId])
                                                       ->one();

        if (Yii::$app->getUser()->identity->getIsLawyer() && $model->status_id === AppointmentStatus::STATUS_PENDING_REVIEW) {
            $this->citizenAppointmentsService->markAppointmentAsReceivedByLawyer($model);
        }

        return $this->render('view', compact('model'));
    }

    public function actionCreate()
    {
        $request = Yii::$app->getRequest();
        $model   = new CitizenAppointmentForm;

        if ($request->isGet) {
            return $this->render('form', compact('model'));
        }

        if ($model->load($request->post()) && $model->validate()) {
            $session = Yii::$app->getSession();

            if ($this->citizenAppointmentsService->saveCitizenAppointment($model)) {
                $session->setFlash('success', 'Successfully send your appointment');
            } else {
                $session->setFlash('danger', 'Failed sending your appointment.');
            }
        }

        return $this->redirect(['/user-appointments/index']);
    }

    public function actionUpdate($appointmentId)
    {
        $request = Yii::$app->getRequest();
        $model   = $this->citizenAppointmentsService->fetchAppointment($appointmentId);

        if ($request->isGet) {
            return $this->render('form', compact('model'));
        }

        if ($model->load($request->post())) {
            $session = Yii::$app->getSession();

            if ($this->citizenAppointmentsService->saveCitizenAppointment($model)) {
                $session->setFlash('success', 'Successfully updated your appointment');
            } else {
                $session->setFlash('danger', 'Failed updating your appointment.');
            }
        }

        return $this->redirect(['/user-appointments/index']);
    }

    public function actionDelete($appointmentId)
    {
        $request = Yii::$app->getRequest();

        if (!$request->isAjax || !$request->isPost) {
            throw new BadRequestHttpException('When deleting appointment, request method should be ajax post.');
        }

        $model = Appointments::findOne($appointmentId);

        if (!$model instanceof Appointments) {
            throw new InvalidArgumentException('Requested for deletion appointment cannot be found.');
        }

        $success = false;

        if ($this->citizenAppointmentsService->deleteAppointment($model)) {
            Yii::$app->getSession()->setFlash('success', 'Successfully deleted appointment.');
            $success = true;
        }

        return $this->asJson(compact('success'));
    }

    /**
     * @throws HttpRequestMethodException
     */
    public function actionValidation()
    {
        $request = Yii::$app->getRequest();

        if (!$request->isAjax && !$request->isPost) {
            throw new HttpRequestMethodException('Validation of appointment should be invoked asynchronously.');
        }

        $model = isset($request->post('CitizenAppointmentForm')['id']) ? CitizenAppointmentForm::findOne($request->post('CitizenAppointmentForm')['id'])
                                                                             : new CitizenAppointmentForm;

        $model->scenario = CitizenAppointmentForm::SCENARIO_VALIDATION;

        if (!$model->load($request->post())) {
            throw new InvalidArgumentException('Passed data cannot be applied successfully.');
        }

        $modelErrors = [];

        if (!empty($model->start_date) && !empty($model->end_date)
            && (!empty($model->lawyerId) || (!$model->isNewRecord && (int) $model->status_id === AppointmentStatus::STATUS_REJECTED)))
        {
            $lawyerAssignedAppointments = $this->citizenAppointmentsService->fetchLawyerApprovedAppointmentsByScheduledDate($model->lawyerId, $model->start_date, $model->end_date);

            if (!empty($lawyerAssignedAppointments)) {
                $modelErrors[Html::getInputId($model, 'lawyerId')] = ['Lawyer has already another approved appointments on this period.'];
            }

            if ($this->citizenAppointmentsService->hasRejectedAppointmentOverlappingDates($model)) {
                $modelErrors[Html::getInputId($model, 'start_date')] = ['Rejected appointment should not overlap previous start date.'];
                $modelErrors[Html::getInputId($model, 'end_date')]   = ['Rejected appointment should not overlap previous end date.'];
            }
        }

        return $this->asJson(array_merge(ActiveForm::validate($model), $modelErrors));
    }
}

controllers/LawyerAppointmentsController.php
<?php

namespace app\controllers;

use app\models\dto\ApproveOrRejectAppointmentForm;
use app\services\LawyerAppointmentsServiceInterface;
use Yii;
use yii\base\Module;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\Response;

class LawyerAppointmentsController extends Controller
{
    /**
     * @var LawyerAppointmentsServiceInterface $lawyerAppointmentsService
     */
    private $lawyerAppointmentsService;

    /**
     * LawyerAppointmentsController constructor.
     * @param string $id
     * @param Module $module
     * @param LawyerAppointmentsServiceInterface $lawyerAppointmentsService
     * @param array $config
     */
    public function __construct(string $id,
                                Module $module,
                                LawyerAppointmentsServiceInterface $lawyerAppointmentsService,
                                array $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->lawyerAppointmentsService = $lawyerAppointmentsService;
    }

    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow'      => true,
                        'actions'    => ['approve-or-reject'],
                        'roles'      => ['approveAppointment', 'Lawyer'],
                        'roleParams' => function () {
                            return ['appointmentId' => Yii::$app->request->get('appointmentId')];
                        },
                    ],
                ],
            ],
        ];
    }

    /**
     * @param $appointmentId
     * @return Response
     */
    public function actionApproveOrReject($appointmentId)
    {
        $model   = ApproveOrRejectAppointmentForm::findOne($appointmentId);
        $session = Yii::$app->getSession();

        if ($model->load($_POST) && $this->lawyerAppointmentsService->processAppointment($model)) {
            $actionMessageSuffix = $this->lawyerAppointmentsService->getSuffixSuccessfullyProcessedAppointment($model);
            $message             = 'Successfully ' . strtolower($model->action) . $actionMessageSuffix . ' citizen appointment';
            $session->setFlash('success', $message);
        } else {
            $session->setFlash('danger', 'Failed processing citizen appointment');
        }

        return $this->redirect(Url::to(['/user-appointments/index']));
    }
}

views/citizen-appointments/_approve_appointment.php
<?php

/* @var $this View */
/* @var $model ApproveOrRejectAppointmentForm */

use app\models\dto\ApproveOrRejectAppointmentForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\ActiveForm;

$form = ActiveForm::begin([
    'options' => ['class' => 'approve-appointment-form'],
    'action'  => Url::to(['/lawyer-appointments/approve-or-reject', 'appointmentId' => $model->id]),
    'method'  => 'POST'
]);

$name = "{$model->formName()}[action]";

echo Html::submitButton('Approve', ['name' => $name, 'value' => 'Approve', 'class' => 'btn btn-success']);

echo Html::submitButton('Reject', ['name' => $name, 'value' => 'Reject', 'class' => 'btn btn-danger']);

ActiveForm::end();

views/citizen-appointments/form.php
<?php

/* @var $this View */
/* @var $model CitizenAppointmentForm */

use app\models\AppointmentStatus;
use app\models\dto\CitizenAppointmentForm;
use app\models\Users;
use app\models\UserType;
use app\widgets\DelaSportDateTimePickerWidget;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\ActiveForm;

$activeLawyers = Users::find()->where(['type_id' => UserType::LAWYER])->all();

$form = ActiveForm::begin([
    'options'                => ['class' => 'appointment-form'],
    'enableAjaxValidation'   => true,
    'enableClientValidation' => false,
    'validationUrl'          => Url::to(['/citizen-appointments/validation'])
]);

if (!$model->isNewRecord) {
    $this->title = 'Update Appointment: ' . '<b>' . $model->name . '</b>';

    echo $form->field($model, 'id')->hiddenInput()->label(false);
    echo $form->field($model, 'status_id')->hiddenInput()->label(false);
} else {
    $this->title = 'Create Appointment';
}

$this->params['breadcrumbs'][] = $this->title;

echo $form->field($model, 'name')->textInput();

echo $form->field($model, 'description')->textarea();

if ($model->isNewRecord || $model->status_id === AppointmentStatus::STATUS_REJECTED) { ?>

    <div class="row">
        <div class="col-xs-6">
            <b>Rejected Start Date: </b>
            <span><?= $model->start_date; ?></span>
        </div>

        <div class="col-xs-6">
            <b>Rejected End Date: </b>
            <span><?= $model->end_date; ?></span>
        </div>
    </div>

    <?php $model->start_date = null;
    $model->end_date   = null;

    echo $form->field($model, 'start_date')->widget(DelaSportDateTimePickerWidget::class);

    echo $form->field($model, 'end_date')->widget(DelaSportDateTimePickerWidget::class);
} else {
    if (!$model->isNewRecord && $model->status_id !== AppointmentStatus::STATUS_REJECTED) { ?>
        <div class="row">
            <div class="col-xs-4">
                <b>Start Date: </b>
                <span><?= $model->start_date; ?></span>
            </div>

            <div class="col-xs-4">
                <b>End Date: </b>
                <span><?= $model->end_date; ?></span>
            </div>

            <div class="col-xs-4">
                <b>Status: </b>
                <span><?= $model->status->name; ?></span>
            </div>
        </div>
    <?php }
}

if ($model->isNewRecord) {
    echo $form->field($model, 'lawyerId')->dropDownList(ArrayHelper::map($activeLawyers, 'id', function (Users $lawyer) {
        return $lawyer->first_name . ' ' . $lawyer->last_name;
    }), ['prompt' => 'Choose Lawyer']);
} else {
    echo $form->field($model, 'lawyerId')->textInput(['disabled' => 'disabled', 'value' => $model->userAppointment->lawyer->first_name . ' ' . $model->userAppointment->lawyer->last_name]);
}

$submitButtonTitle = $model->isNewRecord ? 'Send Appointment' : 'Update Appointment';

echo Html::submitButton($submitButtonTitle, ['class' => 'btn btn-success']);

ActiveForm::end(); ?>

<script>
    $(function () {
        let $form = $('.appointment-form');

        $form.on('ajaxComplete', function(event, jqXHR) {
            $form.yiiActiveForm('updateMessages', jqXHR.responseJSON, true);
            $form.yiiActiveForm('data').validated = Object.values(jqXHR.responseJSON).filter(x => x.length !== 0).length ? false : true;
        });
    });
</script>

views/citizen-appointments/view.php
<?php

/* @var $this View */
/* @var $model ApproveOrRejectAppointmentForm */

use app\models\AppointmentStatus;
use app\models\dto\ApproveOrRejectAppointmentForm;
use yii\helpers\Html;
use yii\web\Response;
use yii\web\View;
use yii\widgets\DetailView;

echo Html::tag('h3', 'Appointment Request');

echo DetailView::widget([
    'model'      => $model,
    'attributes' => [
        'name',
        'description',
        [
            'attribute' => 'citizen',
            'label'     => 'Sent From',
            'value'     => function (ApproveOrRejectAppointmentForm $appointment) {
                $citizen = $appointment->userAppointment->citizen;
                return $citizen->first_name . ' ' . $citizen->last_name;
            }
        ],
        [
            'attribute' => 'lawyer',
            'label'     => 'Sent To',
            'value'     => function (ApproveOrRejectAppointmentForm $appointment) {
                $lawyer = $appointment->userAppointment->lawyer;
                return 'You (' . $lawyer->first_name . ' ' . $lawyer->last_name . ')';
            }
        ],
        [
            'attribute' => 'created_date',
            'format'    => Response::FORMAT_RAW
        ],
        [
            'attribute' => 'updated_date',
            'format'    => Response::FORMAT_RAW
        ],
        [
            'attribute' => 'start_date',
            'format'    => Response::FORMAT_RAW
        ],
        [
            'attribute' => 'end_date',
            'format'    => Response::FORMAT_RAW
        ],
        [
            'attribute' => 'status.name',
            'label'     => 'Status'
        ]
    ]
]);

if (Yii::$app->user->identity->getIsLawyer()
    && array_search($model->status_id, [AppointmentStatus::STATUS_PENDING_REVIEW, AppointmentStatus::STATUS_RECEIVED, AppointmentStatus::STATUS_RESCHEDULED])
    && Yii::$app->user->can('approveAppointment', ['appointmentId' => $model->id]))
{
    echo $this->render('_approve_appointment', compact('model'));
}