models/UserAppointments.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "user_appointments".
 *
 * @property int $citizen_id
 * @property int $lawyer_id
 * @property int $appointment_id
 *
 * @property Appointments $appointment
 * @property Users $citizen
 * @property Users $lawyer
 */
class UserAppointments extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user_appointments';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['citizen_id', 'lawyer_id', 'appointment_id'], 'required'],
            [['citizen_id', 'lawyer_id', 'appointment_id'], 'default', 'value' => null],
            [['citizen_id', 'lawyer_id', 'appointment_id'], 'integer'],
            [['citizen_id', 'lawyer_id', 'appointment_id'], 'unique', 'targetAttribute' => ['citizen_id', 'lawyer_id', 'appointment_id']],
            [['appointment_id'], 'exist', 'skipOnError' => true, 'targetClass' => Appointments::class, 'targetAttribute' => ['appointment_id' => 'id']],
            [['citizen_id'], 'exist', 'skipOnError' => true, 'targetClass' => Users::class, 'targetAttribute' => ['citizen_id' => 'id']],
            [['lawyer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Users::class, 'targetAttribute' => ['lawyer_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'citizen_id' => 'Citizen ID',
            'lawyer_id' => 'Lawyer ID',
            'appointment_id' => 'Appointment ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAppointment()
    {
        return $this->hasOne(Appointments::class, ['id' => 'appointment_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCitizen()
    {
        return $this->hasOne(Users::class, ['id' => 'citizen_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLawyer()
    {
        return $this->hasOne(Users::class, ['id' => 'lawyer_id']);
    }

    /**
     * {@inheritdoc}
     * @return UserAppointmentsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UserAppointmentsQuery(get_called_class());
    }
}

controllers/CitizenAppointmentsController.php
<?php

namespace app\controllers;

use app\models\Appointments;
use app\models\AppointmentStatus;
use app\models\dto\ApproveOrRejectAppointmentForm;
use app\models\dto\CitizenAppointmentForm;
use app\services\CitizenAppointmentsServiceInterface;
use http\Exception\InvalidArgumentException;
use HttpRequestMethodException;
use Yii;
use yii\base\Module;
use yii\filters\AccessControl;
use yii\helpers\Html;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\widgets\ActiveForm;

class CitizenAppointmentsController extends Controller
{
    /**
     * @var CitizenAppointmentsServiceInterface $citizenAppointmentsService
     */
    private $citizenAppointmentsService;

    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow'      => true,
                        'actions'    => ['view'],
                        'roles'      => ['previewAppointment'],
                        'roleParams' => function() {
                            return ['appointmentId' => Yii::$app->request->get('appointmentId')];
                        },
                    ],
                    [
                        'allow'      => true,
                        'actions'    => ['create', 'validation'],
                        'roles'      => ['Citizen']
                    ],
                    [
                        'allow'      => true,
                        'actions'    => ['update'],
                        'roles'      => ['updateAppointment', 'Citizen'],
                        'roleParams' => function() {
                            return ['appointmentId' => Yii::$app->request->get('appointmentId')];
                        },
                    ],
                    [
                        'allow'      => true,
                        'actions'    => ['delete'],
                        'roles'      => ['deleteAppointment'],
                        'roleParams' => function() {
                            return ['appointmentId' => Yii::$app->request->get('appointmentId')];
                        },
                    ]
                ],
            ],
        ];
    }

    /**
     * CitizenAppointmentsController constructor.
     * @param string $id
     * @param Module $module
     * @param CitizenAppointmentsServiceInterface $citizenAppointmentsService
     * @param array $config
     */
    public function __construct(string $id,
                                Module $module,
                                CitizenAppointmentsServiceInterface $citizenAppointmentsService,
                                array $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->citizenAppointmentsService = $citizenAppointmentsService;
    }

    public function actionView($appointmentId)
    {
        $model = ApproveOrRejectAppointmentForm::find()->joinWith(['userAppointment', 'status'])
                                                       ->where(['appointments.id' => $appointmentId])
                                                       ->one();

        if (Yii::$app->getUser()->identity->getIsLawyer() && $model->status_id === AppointmentStatus::STATUS_PENDING_REVIEW) {
            $this->citizenAppointmentsService->markAppointmentAsReceivedByLawyer($model);
        }

        return $this->render('view', compact('model'));
    }

    public function actionCreate()
    {
        $request = Yii::$app->getRequest();
        $model   = new CitizenAppointmentForm;

        if ($request->isGet) {
            return $this->render('form', compact('model'));
        }

        if ($model->load($request->post()) && $model->validate()) {
            $session = Yii::$app->getSession();

            if ($this->citizenAppointmentsService->saveCitizenAppointment($model)) {
                $session->setFlash('success', 'Successfully send your appointment');
            } else {
                $session->setFlash('danger', 'Failed sending your appointment.');
            }
        }

        return $this->redirect(['/user-appointments/index']);
    }

    public function actionUpdate($appointmentId)
    {
        $request = Yii::$app->getRequest();
        $model   = $this->citizenAppointmentsService->fetchAppointment($appointmentId);

        if ($request->isGet) {
            return $this->render('form', compact('model'));
        }

        if ($model->load($request->post())) {
            $session = Yii::$app->getSession();

            if ($this->citizenAppointmentsService->saveCitizenAppointment($model)) {
                $session->setFlash('success', 'Successfully updated your appointment');
            } else {
                $session->setFlash('danger', 'Failed updating your appointment.');
            }
        }

        return $this->redirect(['/user-appointments/index']);
    }

    public function actionDelete($appointmentId)
    {
        $request = Yii::$app->getRequest();

        if (!$request->isAjax || !$request->isPost) {
            throw new BadRequestHttpException('When deleting appointment, request method should be ajax post.');
        }

        $model = Appointments::findOne($appointmentId);

        if (!$model instanceof Appointments) {
            throw new InvalidArgumentException('Requested for deletion appointment cannot be found.');
        }

        $success = false;

        if ($this->citizenAppointmentsService->deleteAppointment($model)) {
            Yii::$app->getSession()->setFlash('success', 'Successfully deleted appointment.');
            $success = true;
        }

        return $this->asJson(compact('success'));
    }

    /**
     * @throws HttpRequestMethodException
     */
    public function actionValidation()
    {
        $request = Yii::$app->getRequest();

        if (!$request->isAjax && !$request->isPost) {
            throw new HttpRequestMethodException('Validation of appointment should be invoked asynchronously.');
        }

        $model = isset($request->post('CitizenAppointmentForm')['id']) ? CitizenAppointmentForm::findOne($request->post('CitizenAppointmentForm')['id'])
                                                                             : new CitizenAppointmentForm;

        $model->scenario = CitizenAppointmentForm::SCENARIO_VALIDATION;

        if (!$model->load($request->post())) {
            throw new InvalidArgumentException('Passed data cannot be applied successfully.');
        }

        $modelErrors = [];

        if (!empty($model->start_date) && !empty($model->end_date)
            && (!empty($model->lawyerId) || (!$model->isNewRecord && (int) $model->status_id === AppointmentStatus::STATUS_REJECTED)))
        {
            $lawyerAssignedAppointments = $this->citizenAppointmentsService->fetchLawyerApprovedAppointmentsByScheduledDate($model->lawyerId, $model->start_date, $model->end_date);

            if (!empty($lawyerAssignedAppointments)) {
                $modelErrors[Html::getInputId($model, 'lawyerId')] = ['Lawyer has already another approved appointments on this period.'];
            }

            if ($this->citizenAppointmentsService->hasRejectedAppointmentOverlappingDates($model)) {
                $modelErrors[Html::getInputId($model, 'start_date')] = ['Rejected appointment should not overlap previous start date.'];
                $modelErrors[Html::getInputId($model, 'end_date')]   = ['Rejected appointment should not overlap previous end date.'];
            }
        }

        return $this->asJson(array_merge(ActiveForm::validate($model), $modelErrors));
    }
}

controllers/UserAppointmentsController.php
<?php

namespace app\controllers;

use app\models\searches\UserAppointmentsSearch;
use yii\web\Controller;

class UserAppointmentsController extends Controller
{
    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel  = new UserAppointmentsSearch;
        $dataProvider = $searchModel->search($_GET);
        return $this->render('index', compact('searchModel', 'dataProvider'));
    }
}

views/user-appointments/_grid.php
<?php

/* @var $this View */
/* @var $dataProvider ActiveDataProvider */

use app\models\UserAppointments;
use rmrevin\yii\fontawesome\FAS;
use yii\data\ActiveDataProvider;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View; ?>

<div class="row">
    <div class="col-xs-12">
        <?php
            if (Yii::$app->getUser()->identity->getIsCitizen()) {
                echo Html::tag('h3', 'My Appointments');
            } else {
                echo Html::tag('h3', 'Requested Appointments');
            }
        ?>
        <?= GridView::widget([
            'options'      => ['class' => 'table-responsive grid-view'],
            'dataProvider' => $dataProvider,
            'columns'      => [
                [
                    'attribute' => 'citizen',
                    'value'     => function (UserAppointments $userAppointment) {
                        return $userAppointment->citizen->first_name . ' ' . $userAppointment->citizen->last_name;
                    }
                ],
                [
                    'attribute' => 'lawyer',
                    'value'     => function (UserAppointments $userAppointment) {
                        return $userAppointment->lawyer->first_name . ' ' . $userAppointment->lawyer->last_name;
                    }
                ],
                'appointment.name',
                'appointment.description',
                [
                    'attribute' => 'appointment.status.name',
                    'label'     => 'Status'
                ],
                'appointment.start_date',
                'appointment.end_date',
                'appointment.created_date',
                'appointment.updated_date',
                [
                    'class'          => ActionColumn::class,
                    'template'       => '{view} {update} {delete}',
                    'visibleButtons' => [
                        'view'   => function (UserAppointments $userAppointment) {
                            return Yii::$app->user->can('previewAppointment', ['appointmentId' => $userAppointment->appointment_id]);
                        },
                        'update' => function (UserAppointments $userAppointment) {
                            return Yii::$app->getUser()->can('updateAppointment', ['appointmentId' => $userAppointment->appointment_id]);
                        },
                        'delete' => function (UserAppointments $userAppointment) {
                            return Yii::$app->getUser()->can('deleteAppointment', ['appointmentId' => $userAppointment->appointment_id]);
                        }
                    ],
                    'buttons'  => [
                        'view'   => function ($url, UserAppointments $userAppointment) {
                            return Html::a(FAS::icon(FAS::_EYE), Url::to(['/citizen-appointments/view', 'appointmentId' => $userAppointment->appointment_id]));
                        },
                        'update' => function ($url, UserAppointments $userAppointment) {
                            return Html::a(FAS::icon(FAS::_PENCIL_ALT), Url::to(['/citizen-appointments/update', 'appointmentId' => $userAppointment->appointment_id]));
                        },
                        'delete' => function ($url, UserAppointments $userAppointment) {
                            return Html::button(FAS::icon(FAS::_TRASH_ALT), [
                                'class'    => 'js-delete-appointment',
                                'data-url' => Url::to(['/citizen-appointments/delete', 'appointmentId' => $userAppointment->appointment_id])
                            ]);
                        }
                    ]
                ]
            ]
        ]); ?>
    </div>
</div>

views/user-appointments/_search.php
<?php

/* @var $this View */
/* @var $searchModel UserAppointmentsSearch */

use app\models\AppointmentStatus;
use app\models\searches\UserAppointmentsSearch;
use app\widgets\DelaSportDateTimePickerWidget;
use yii\bootstrap\Modal;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\ActiveForm;

$form = ActiveForm::begin([
    'method' => 'GET',
    'action' => Url::to(["/user-appointments"])
]);

echo $form->field($searchModel, 'commonFilter')->textInput([
    'placeholder' => $searchModel->getAttributeLabel('commonFilter')
])->label(false);

if (!empty($searchModel->startDateRange) && !empty($searchModel->endDateRange)) {
    $searchModel->startDateRange = Yii::$app->getFormatter()->asDatetime($searchModel->startDateRange, 'MM/dd/Y HH:i');
    $searchModel->endDateRange   = Yii::$app->getFormatter()->asDatetime($searchModel->endDateRange, 'MM/dd/Y HH:i');
}

if (!empty($searchModel->startCreatedDateRange) && !empty($searchModel->endCreatedDateRange)) {
    $searchModel->startCreatedDateRange = Yii::$app->getFormatter()->asDatetime($searchModel->startCreatedDateRange, 'MM/dd/Y HH:i');
    $searchModel->endCreatedDateRange   = Yii::$app->getFormatter()->asDatetime($searchModel->endCreatedDateRange, 'MM/dd/Y HH:i');
}

if (!empty($searchModel->startUpdatedDateRange) && !empty($searchModel->endUpdatedDateRange)) {
    $searchModel->startUpdatedDateRange = Yii::$app->getFormatter()->asDatetime($searchModel->startUpdatedDateRange, 'MM/dd/Y HH:i');
    $searchModel->endUpdatedDateRange   = Yii::$app->getFormatter()->asDatetime($searchModel->endUpdatedDateRange, 'MM/dd/Y HH:i');
}

echo Html::button(Html::a('Reset Filters', Url::to(["/user-appointments"])));

Modal::begin([
    'toggleButton' => [
        'tag'   => 'button',
        'label' => 'Additional Filters',
        'class' => 'btn btn-success'
    ]
]); ?>

<?= $form->field($searchModel, 'startDateRange')->widget(DelaSportDateTimePickerWidget::class); ?>

<?= $form->field($searchModel, 'endDateRange')->widget(DelaSportDateTimePickerWidget::class); ?>

<hr/>

<?= $form->field($searchModel, 'startCreatedDateRange')->widget(DelaSportDateTimePickerWidget::class); ?>

<?= $form->field($searchModel, 'endCreatedDateRange')->widget(DelaSportDateTimePickerWidget::class); ?>

<hr/>

<?= $form->field($searchModel, 'startUpdatedDateRange')->widget(DelaSportDateTimePickerWidget::class); ?>

<?= $form->field($searchModel, 'endUpdatedDateRange')->widget(DelaSportDateTimePickerWidget::class); ?>

<hr/>

<?= $form->field($searchModel, 'appointmentStatusId')->dropDownList(ArrayHelper::map(AppointmentStatus::find()->all(), 'id', 'name'), [
    'prompt' => 'Filter By Status'
]); ?>

<?php

echo Html::submitButton('Search', ['class' => 'btn btn-success']);

Modal::end();

ActiveForm::end();

views/user-appointments/index.php
<?php

/* @var $this View */
/* @var $searchModel UserAppointmentsSearch */
/* @var $dataProvider ActiveDataProvider */

use app\models\searches\UserAppointmentsSearch;
use rmrevin\yii\fontawesome\FAS;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

echo $this->render('_search', compact('searchModel'));

if (Yii::$app->getUser()->identity->getIsCitizen()) {
    echo Html::a(FAS::icon(FAS::_PLUS), Url::to(['/citizen-appointments/create']), [
        'data-toggle' => 'tooltip',
        'title'       => 'Add Appointment'
    ]);
}

echo $this->render('_grid', compact('dataProvider')); ?>

<script>
    $(function () {
        $('.js-delete-appointment').on('click', function () {
            let $button = $(this);
            
            $.post($button.data('url'), function (response) {
                if (response.success) {
                    location.reload();
                    return;
                }

                Swal.fire(
                    'Failed deleting appointment.',
                    'error'
                );
            });
        });
    });
</script>